# Generated by Django 3.1.4 on 2021-01-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(default='')),
                ('make', models.TextField(default='')),
                ('year', models.IntegerField(default=0)),
                ('co2', models.FloatField(default=None, null=True)),
                ('co', models.FloatField(default=None, null=True)),
                ('n2o', models.FloatField(default=None, null=True)),
            ],
        ),
    ]
