# Generated by Django 3.1.4 on 2021-01-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='car_model',
        ),
    ]
