# Generated by Django 3.1.4 on 2021-01-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0002_auto_20210123_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('iq3', models.FloatField()),
                ('median', models.FloatField()),
                ('iq1', models.FloatField()),
                ('average', models.FloatField()),
            ],
        ),
    ]
